apiVersion: apps/v1
kind: Deployment
metadata:
  name: %nameSpace%
  namespace: %nameSpace%
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: %nameSpace%
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: %nameSpace%
    spec:
      containers:
      - image: harbor.%dnsSuffix%/%nameSpace%/mypython:XXXXXX
        imagePullPolicy: Always
        name: %nameSpace%
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: pull-secret
      dnsPolicy: ClusterFirst
      imagePullSecret: pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30