apiVersion: v1
kind: Service
metadata:
  name: %nameSpace%
  namespace: %nameSpace%  # Specify the namespace
spec:
  selector:
    app: %nameSpace%  # Match pods with the label app=%nameSpace%
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: ClusterIP  # Default service type (accessible only within the cluster)
